---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/quotes":
    get:
      summary: list all quotes
      parameters: []
      responses:
        '200':
          description: successful
    post:
      summary: create quote
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                author:
                  type: string
              required:
              - content
              - author
  "/quotes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show quote
      responses:
        '200':
          description: successful
    put:
      summary: update quote
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                author:
                  type: string
              required:
              - id
              - content
              - author
    delete:
      summary: delete quote
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
